name: unipi_orario
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_i18n: ^0.36.2
  dynamic_color: ^1.7.0
  animated_theme_switcher: ^2.0.10
  universal_io: ^2.2.2
  device_info_plus: ^10.1.2
  shared_preferences: ^2.3.2
  easy_date_timeline: ^1.1.3
  expandable_page_view: ^1.0.17
  unipi_orario_wrapper:
    path: ../wrapper

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/i18n/

  uses-material-design: true
